#pragma once

#define PLIC_BASE_ADDR 0xc000000

#define READER_DONE_IRQ_NUM 0x30
#define WRITER_DONE_IRQ_NUM 0x31
#define DECODE_DONE_IRQ_NUM 0x32

#define PLIC_PRIORITY_BASE_ADDR (PLIC_BASE_ADDR + 0x00000000)
#define PLIC_PENDING_BASE_ADDR (PLIC_BASE_ADDR + 0x00001000)
#define PLIC_ENABLE_BASE_ADDR (PLIC_BASE_ADDR + 0x00002000)
#define PLIC_THRESHOLD_ADDR (PLIC_BASE_ADDR + 0x200000)
#define PLIC_CLAIM_COMPLETE_ADDR (PLIC_BASE_ADDR + 0x200004)

#define PLIC_PRIORITY_ADDR(plic_int) (PLIC_PRIORITY_BASE_ADDR + (4 * plic_int))
#define PLIC_PENDING_ADDR(plic_int) (PLIC_PENDING_BASE_ADDR + (4 * (plic_int / 32)))
#define PLIC_ENABLE_ADDR(plic_int) (PLIC_ENABLE_BASE_ADDR + (4 * plic_int))

#define PLIC_VECTOR_BITSHIFT(plic_int) (1 << (plic_int % 32))

#define PLIC_BASE_PRIORITY 0x2
#define PLIC_BASE_THRESHOLD 0x1
